apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    component: web
  type: NodePort
  ports:
    - name: client-nod-port
      port: 3050
      targetPort: 9000
      nodePort: 31515
